### ISSUE TITLE
Data preprocessing pattern

### ISSUE THREAD

**Issue by vereba** [viadee/bpmn.ai-patterns#16]
## Division of data preprocessing into destructive and non-destructive steps

Data preprocessing is crucial in any data mining process as they directly impact success rate of the ML model.
One can say that preprocessing steps can be categorized into non-destructive operations, where the representation of the feature before transformation is restorable, and destructive operations, non-bijective and therefore irreversible.

Non-destructive processing steps are for example:
- changing the data type without loss of information (string to category/number), integer to float)
- Data cleansing in the form of removing data instances or features without information content, with many corrupt, missing or invalid values
- Construct new features from existing ones

Destructive:
- Change of data type with loss of information (float to int)
- Aggregation of values to bins (numeric) or category ("light blue" and "navy blue" to "blue")
- Replace missing values
- Replace feature(s) with constructed feature(s)

It is recommended to first perform all non-destructive and then all destructive operations. A division of the preprocessing procedure into these categories allows a comparison of the not corrupted but structured, prepared data (result of non-destructive operations) with the Engineered Features, which serve as input to the model. This way it can be traced which feature-changing steps have been performed and it can be ensured that the structure of the data is not fundamentally changed or corrupted, for example that strong dependencies are not broken. Possible errors, which are transferred from the data to the resulting model, can be uncovered.

Remark: Although standardization and normalization are, in case the scaler is saved, non-destructive too, it is better to apply it as a last step in order to keep the data human understandable.

**Comment by fkoehne** [comment]
Thank you. I finally found the time to include the pattern in the text - it is currently the cornerstone of the training chapter, which I think might grow further.
https://github.com/viadee/bpmn.ai-patterns/commit/cb2e271a3218c1812d89663d0dcc6c1bb455188e
